[package]
name = "contract"
version = "0.1.0"
authors = ["karandh <karan@casperlabs.io>","Maciej Zieliński <maciej@casperlabs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contract = { git="https://github.com/CasperLabs/CasperLabs", branch="dev", package = "casperlabs-contract" }
types = { git="https://github.com/CasperLabs/CasperLabs", branch="dev", package = "casperlabs-types" }
contract_macro = { git = "https://github.com/CasperLabs/casperlabs_contract_macro", branch = "ECO-608-Support-CL-Types", package = "contract_macro"}

[lib]
crate-type = ["cdylib"]
doctest = false
test = false
bench = false

[features]
default = ["contract/std", "types/std"]
